name: Test Build

on: workflow_dispatch

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions-rust-lang/setup-rust-toolchain@v1
            - uses: arduino/setup-protoc@v3
            - name: Prepare build targets 
              run: |
                rustup target add aarch64-apple-darwin
                rustup target add aarch64-unknown-linux-gnu
                rustup target add x86_64-apple-darwin
                rustup target add x86_64-pc-windows-msvc
                rustup target add x86_64-unknown-linux-gnu
            - name: Build for all targets
              run: | 
                cargo build --release --target aarch64-apple-darwin
                cargo build --release --target aarch64-unknown-linux-gnu
                cargo build --release --target x86_64-apple-darwin
                cargo build --release --target x86_64-pc-windows-msvc
                cargo build --release --target x86_64-unknown-linux-gnu
            - name: Get Package Version
              id: get_package_version
              run: echo "PACKAGE_VERSION=$(cargo pkgid | cut -d '#' -f 2 | cut -d ':' -f 2)" >> $GITHUB_ENV
            - run: echo Built for version ${{ env.PACKAGE_VERSION }}
            - run: cargo run