name: Test Build

on: workflow_dispatch

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions-rust-lang/setup-rust-toolchain@v1
            - uses: arduino/setup-protoc@v3
            - run: cargo build
            - run: cargo run