name: Test Build

on: workflow_dispatch

jobs:
    build:
        strategy:
            matrix:
                include:
                    - TARGET: x86_64-unknown-linux-gnu # tested in a debian container on a mac
                      OS: ubuntu-latest
                    - TARGET: aarch64-apple-darwin
                      OS: macos-latest
        runs-on: ${{ matrix.OS }}
        steps:
            - uses: actions/checkout@v4
            - uses: actions-rust-lang/setup-rust-toolchain@v1
            - uses: arduino/setup-protoc@v3
              with:
                repo-token: ${{ secrets.GITHUB_TOKEN }}
            - name: Build for current target
              run: | 
                cargo build --release --target ${{ matrix.TARGET }}
            - name: Get Package Version
              run: echo "PACKAGE_VERSION=$(cargo pkgid | cut -d '#' -f 2 | cut -d ':' -f 2)" >> $GITHUB_ENV
            - name: Running examples
              run: | 
                echo Built for version ${{ env.PACKAGE_VERSION }}
                cargo run