name: Test Stuff

on: workflow_dispatch

defaults:
  run:
    # necessary for windows
    shell: bash

jobs:    
    update-installer-latest-version:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4.1.7
          name: Fetch entire history (for conventional commits)
          with:
            fetch-depth: 0
        - name: Configure Git
          run: |
            git config --global user.name GitHub Actions
            git config user.email github-actions@github.com
        - name: Install Knope
          uses: knope-dev/action@v2.1.0
          with:
            version: 0.18.0
        - name: Update Installer version
          run: | 
            VERSION=$(knope get-version)

            sed -i "s/PACKAGE_VERSION=\"v[0-9]*\.[0-9]*\.[0-9]*\"/PACKAGE_VERSION=\"v$VERSION\"/" installers/nix/install.sh